services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-fetcher-container
    ports:
      - "4000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
    command: >
      sh -c "cd server && python app.py"
    tty: true
    stdin_open: true
    # Mount the local app.py (flask server) file to the container
    # Mount also the frontend js files
    volumes:
      - ./server/app.py:/app/server/app.py
      - ./client/:/app/client/
