services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./client/src:/app/client/src
      - ./client/index.html:/app/clint/index.html
    depends_on: 
      - backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./server/app.py:/app/server/app.py
      - ./server/db_to_json.py:/app/server/db_to_json.py
